### ISSUE TITLE
Differentiate between original repos and forks

### ISSUE THREAD

**Issue by pithyless** [robertgreiner/gitcv#1]
I think it would be informative for GitCV to differentiate between original repos and forks of existing projects.

GitHub api already returns this information and it is stored in `GithubRepository` as `public bool fork { get; set; }`.

One possibility would be to add another column to the results table and display repos sorted by fork status and name:

``` c#
// HomeController.cs

user = GithubService.GetUser(loginName);
languages = GithubService.GetLanguages(loginName);
repos = GithubService.GetRepositories(loginName);
sortedRepos = repos.OrderBy(r => r.fork).ThenBy(r => r.name);
```

Another possibility would be to display two separate tables (one for original repos, another for forks):

``` c#
user = GithubService.GetUser(loginName);
languages = GithubService.GetLanguages(loginName);
repos = GithubService.GetRepositories(loginName);
originalRepos = repos.Where(r => r.fork == True).OrderBy(r => r.name)
forkedRepos = repos.Where(r => r.fork == False).OrderBy(r => r.name)
```

**Comment by robertgreiner** [comment]
Personally, I kind of like the idea of splitting it up into two different tables.  Maybe I'll start off showing the github user's original repos and have a tab to toggle display of the forked repos?

Showing the forked repos on some level is important to me because it gives potential employers (or anyone else looking at your profile) a view into what contributions you are making to larger OS projects that you did not start.

**Comment by pithyless** [comment]
I like the approach of displaying an original repos table followed by a contribs table (basically an identical layout with different heading).

I agree it's good to show potential employers any contributions you're making; it'd just be nice to tell which projects are yours without having to click through to GitHub. :)

Cheers!

**Comment by robertgreiner** [comment]
Yeah, you are definitely right.  I'll add an extra table and see how it
looks.

On Sun, Mar 18, 2012 at 10:02 AM, Norbert Wjtowicz <
reply@reply.github.com

**Comment by robertgreiner** [comment]
Fixed.  I'm uploading to gitcv.com right now.
